services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/edo_dodo
      - APP_UPLOADS_DIR=/app/uploads  # ← Путь ВНУТРИ контейнера
    volumes:
      - uploads:/app/uploads

  frontend:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
volumes:
  uploads:
  mongo_data: